spring.application.name=user-profile-service
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?currentSchema=user_profile_schema
spring.datasource.username=postgres.nshubthsxwpibhbrjxps
spring.datasource.password=codemates@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=user_profile_schema
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
server.port=8082